apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  resources:
    requests:
      # Find storage which has been provisoned ahead of time (already there)
      # Or find storage dynamically provisioned
      storage: 2Gi
  volumeMode: Filesystem
  # - ReadWriteOnce -> can be used by single node
  # - ReadOnlyMany -> multiple nodes can read this volume
  # - ReadWriteMany -> multiple nodes can read and write this volume
  accessModes:
    - ReadWriteOnce
