apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgres-sorage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres
          resources:
            limits:
              memory: "256Mi"
              cpu: "1"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-sorage
              mountPath: /var/lib/postgresql/data
              # Any data inside the container that is stored in mountPath will be sotred 
              # in 'postgres' folder inside of the persistentVolumeClaim
              subPath: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD
